### ISSUE TITLE
Failed to open file /apollo/modules/map/data/carla_town03/default_end_way_point.txt in text mode

### ISSUE THREAD

**Issue by AIasd** [AuroAi/carla_apollo_bridge#7]
Hi,

When I run `. /apollo/scripts/dreamview.sh start_fe`, I encountered the following error:

`[/apollo/bazel-bin/modules/dreamview/dreamview --flagfile=/apollo/modules/common/data/global_flagfile.txt]  E0917 12:56:09.470687 31592 file.cc:73] [dreamview] Failed to open file /apollo/modules/map/data/carla_town03/default_end_way_point.txt in text mode.`

I checked the `/apollo/modules/map/data/carla_town03` folder and it is empty. However, when I cloned and build your version of apollo 5.0.0, there seems to be no error.

**Comment by AngelJA** [comment]
Hello!

That error message is expected and shouldn't prevent anything from running.  I believe this file is only needed when using the 'Default Routing' button on the bottom left of dreamview.

The map folders will appear empty from outside docker since they are mounted volumes.  If you inspect them from inside the apollo dev container you can see the contents.

Closing this for now.  If you continue to have issues feel free to open another issue with the specific problem you're having.

**Comment by curio-code** [comment]
I am facing the same issue ... Because of this, I am unable to lunch any module...
@AngelJA Is there any solution to this?
![Screenshot from 2020-12-15 18-20-35](https://user-images.githubusercontent.com/58219955/102348161-780b9980-3fc7-11eb-9134-6d07f8c8b8e1.png)

**Comment by AngelJA** [comment]
As I mentioned before, this error won't prevent things from running.  If you post more of the output from the terminal where you're running dreamview maybe we can track down the issue.

Since I see the map in your screenshot, it seems you do have communication from the bridge, which is a good sign.

**Comment by curio-code** [comment]
@AngelJA Thank you for your prompt reply, Below is the screenshot of my terminal
![Screenshot from 2020-12-15 18-11-32](https://user-images.githubusercontent.com/58219955/102387727-c08e7b80-3ff6-11eb-8c57-39cb3cbd5860.png)

**Comment by AngelJA** [comment]
It seems you've turned on the controller module but not provided a route and turned on planning/prediction etc.  Try running without the controller first since it doesn't work well anyway.

Follow the instructions in the readme carefully up to here: https://github.com/AuroAi/carla_apollo_bridge#planning and make sure your screen matches what's in the screenshot in each step (for example, red line on the map after you provide a route).
